
events {}

http {
    error_page 403 /error.html;

    server {
        listen 80;
        server_name localhost;

        location = /error.html {
            root /usr/share/nginx/html_custom;
            internal;
        }

        # --- PILAR 1: ZTNA ---
        location / {
            auth_basic "Área Restringida - CORE ZTNA";
            auth_basic_user_file /etc/nginx/.htpasswd;
            proxy_pass http://intranet-app;
        }

        # --- PILAR 2: SWG ---
        location /apuestas {
            return 403;
        }

        # --- PILAR 3: CASB ---
        location /descargar-base-datos {
            return 403;
        }

        # --- PILAR 4: FWaaS (Firewall as a Service) ---
        # NUEVO: Simulamos un intento de acceso a gestión (SSH o Admin)
        # El Firewall aplica una regla de "Denegar todo" desde IPs externas/no admins.
        location /admin-ssh {
            # Esta directiva simula una regla de firewall estricta
            deny all; 
        }
    }
}